### PR TITLE
Added a query parameter to start the page with dark theme

### PR DESCRIPTION
**Pull request by Superredstone**
I wanted to have a widget on my desktop with hackernews and the only one that i could find that i like is this one, but the integrated browser in KDE Plasma doesn't maintain the dark theme between sessions. 

immagine

### CODE REVIEW

**Review by rajatkulkarni95 — COMMENTED** [review]
Can you remove the `package-lock.json`? Project uses `pnpm`

**Comment by rajatkulkarni95** [comment]
Also feel like we can just set `defaultTheme='dark'` here https://github.com/rajatkulkarni95/hckrnws/blob/main/src/pages/_app.tsx#L13C4-L13C20

**Comment by Superredstone** [comment]
> Also feel like we can just set `defaultTheme='dark'` here https://github.com/rajatkulkarni95/hckrnws/blob/main/src/pages/_app.tsx#L13C4-L13C20 instead of doing it via `setTheme` since all you care about is the default to be `dark` right?

This could be a solution as well

**Comment by Superredstone** [comment]
Now it should be fine

**Review by rajatkulkarni95 — APPROVED** [review]
LGTM. Thanks for this! Hope you enjoy the app!

**Pull request merged**
